version: '3.8'

services:
  bot:
    container_name: Omega
    image: palander/omega:latest
    volumes:
      - type: bind
        source: ./data
        target: /data
    restart: always
    env_file:
      - .env