version: '3'

services:
  bot:
    container_name: Theta
    image: palander/theta:latest
    volumes:
      - type: bind
        source: ./data
        target: /home/app/data
    restart: unless-stopped
    env_file:
      - .env
